import { counters } from "@/data/facts";
import React from "react";
import Image from "next/image";
import Counter from "@/components/common/Counter";
export default function Sustainability1() {
  return (
    <div className="wg-create-design style-3 pb-80 pt-100 sustainability-mobile-tight">
      <div className="themesflat-container">
        <div className="row align-items-center">
          <div className="col-lg-6">
            <div className="content">
              <div className="heading-section wow fadeInUp style-1">
                <h6 className="tf-color-green">What is the impact?</h6>
                <div
                  className="main-title sustainability-title-mobile-tight"
                  style={{ color: "#000", fontSize: "36px", lineHeight: "52px" }}
                >
                Not a green estimate. Not a generic report.{" "}<br />
                  <span
                    className="animation-text tf-color-green sustainability-title-sub-mobile-tight"
                    style={{ fontSize: "28px", lineHeight: "40px" }}
                  >
                    A real-time ledger of your project’s environmental footprint.
                  </span>
                </div>
              </div>
              <p style={{ color: "#000000", fontSize: "18px", lineHeight: "30px" }}>
              A Sustainability Digital Twin is an active audit of the physical resources powering your project—from the carbon intensity of materials in the hold to the precise chemical footprint of every onsite delivery.
              <br /><br />
              Unlike a generic carbon report, which provides high-level estimates based on averages, IntelliByld’s Digital Twin captures Ground-Truth data. It accounts for the actual fuel consumed by idle machinery and the real-world waste generated by logistical friction, updating your ESG metrics in real time.
               <br /><br />
               Unlike a static dashboard, our system doesn’t just show you what was wasted—it anticipates where waste will happen. By watching every signal across your supply chain, IntelliByld identifies "Carbon Chokepoints" before they manifest, allowing you to optimize for Green Mark 2025 compliance without sacrificing operational speed.
              </p>
              
              
            </div>
          </div>
          <div className="col-lg-6">
            <div
              className="image wow fadeInUp"
              style={{
                width: "100%",
                maxWidth: 420,
                height: 616,
                marginInline: "auto",
              }}
            >
              <Image
                className="img-01"
                src="/assets/images/bg-section/sustainability1.png"
                alt="Sustainability"
                width={420}
                height={616}
                sizes="(max-width: 991px) 100vw, 420px"
                style={{
                  position: "relative",
                  left: 0,
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  borderRadius: 16,
                }}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
